[package]
name = "hefty"
version = "0.1.0"
edition = "2021"
description = "Parser for streaming data"
license = "MIT"
keywords = ["parser"]
repository = "https://github.com/jongiddy/hefty"

[dependencies]
bytes = "1.5"
either = "1.9"
typle = "0.2.1"
