[package]
name = "hefty"
version = "0.3.0"
edition = "2021"
description = "Parser for streaming data"
license = "MIT"
categories = ["parsing"]
repository = "https://github.com/jongiddy/hefty"
rust-version = "1.65"

[dependencies]
bytes = "1.5"
either = "1.9"
typle = "0.7.12"
